apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: web-app

spec:
  containers:
  - name: web-server-container
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http

  - name: content-updater-container
    image: busybox:latest
    command: ["/bin/sh", "-c", "while true; do wget -O /usr/share/nginx/html/index.html http://example.com/index.html; sleep 3600; done"]
    volumeMounts:
    - name: web-content
      mountPath: /usr/share/nginx/html

  volumes:
  - name: web-content
    emptyDir: {}


# The Pod is named web-app-pod and labeled with app: web-app.
# The Pod contains two containers: web-server-container running the Nginx web server and content-updater-container running a simple sidecar container.
# The web-server-container serves content on port 80.
# The content-updater-container uses the busybox image and periodically fetches content from http://example.com/index.html every hour, updating the content in the shared volume web-content.
